name: Node CI

on:
  push:
    branches: 
      - main
      - develop
      - pruebas
      - pruebas_fs
      - pruebas_cicd 
    paths-ignore:
      - "docs/**"
      
  pull_request:
    branches: 
      - main
      - develop
    paths-ignore:
      - "docs/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@master

      - name: Install 🔧
        run: npm install

      - name: Lint 🧐
        run: npm run lint

      - name: Test 🚨
        run: npm test

      - name: Build 🏗️
        run: npm run build
        

